base_lr: 0.1
batch_size: 4
config: ./config/nturgbd-cross-view/train_joint_tl.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.p2agcn.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
    num_node: 50
  num_class: 16
  num_person: 2
  num_point: 25
model_saved_name: ./runs/ntu_cv_agcn_joint_tl
nesterov: true
num_epoch: 300
num_worker: 0
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
printA: false
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 5
- 11
start_epoch: 200
step:
- 280
- 290
test_batch_size: 4
test_feeder_args:
  data_path: ./data/ShakeFiveP2_tl/xview/val_data_joint.npy
  label_path: ./data/ShakeFiveP2_tl/xview/val_label.pkl
train_feeder_args:
  data_path: ./data/ShakeFiveP2_tl/xview/train_data_joint.npy
  debug: false
  label_path: ./data/ShakeFiveP2_tl/xview/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
transfer_learning: false
warm_up_epoch: 0
weight_decay: 0.0001
weights: ./runs/ntu_cv_agcn_joint_tl-199-3250.pt
work_dir: ./work_dir/ntu/xview/agcn_joint_tl
