base_lr: 0.1
batch_size: 4
config: ./config/nturgbd-cross-view/train_bone.yaml
device:
- 0
eval_interval: 5
feeder: feeders.feeder.Feeder
ignore_weights: []
log_interval: 100
model: model.agcn.Model
model_args:
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: spatial
  num_class: 11
  num_person: 2
  num_point: 25
model_saved_name: ./runs/ntu_cv_agcn_bone
nesterov: true
num_epoch: 50
num_worker: 0
only_train_epoch: 0
only_train_part: false
optimizer: SGD
phase: train
print_log: true
save_interval: 2
save_score: false
seed: 1
show_topk:
- 1
- 5
- 11
start_epoch: 18
step:
- 30
- 40
test_batch_size: 4
test_feeder_args:
  data_path: ./data/ntu/xview/val_data_bone.npy
  label_path: ./data/ntu/xview/val_label.pkl
train_feeder_args:
  data_path: ./data/ntu/xview/train_data_bone.npy
  debug: false
  label_path: ./data/ntu/xview/train_label.pkl
  normalization: false
  random_choose: false
  random_move: false
  random_shift: false
  window_size: -1
warm_up_epoch: 0
weight_decay: 0.0001
weights: ./runs/ntu_cv_agcn_joint-17-30996.pt
work_dir: ./work_dir/ntu/xview/agcn_bone
