# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ShakeFive/xview/val_data_joint.npy
  label_path: ./data/ShakeFive/xview/val_label.pkl
  debug: False

# model
model: model.agcn.Model
model_args:
  num_class: 60
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
    num_node: 25


# test 
phase: test
device: [0]
test_batch_size: 64
weights: ./runs/ntu_cv_agcn_joint-49-29400.pt

work_dir: ./work_dir/ntu/xview/agcn_test_joint_SF
model_saved_name: ./runs/ntu_cv_agcn_test_joint_SF
save_score: True