# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ShakeFiveP2_pre2/xview/val_data_joint.npy
  label_path: ./data/ShakeFiveP2_pre2/xview/val_label.pkl
  debug: False

# model
model: model.p2agcn.Model
model_args:
  num_class: 11
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
    num_node: 50


# test 
phase: test
device: [0]
test_batch_size: 64
weights: ./runs/ntu_cv_p2agcn_joint_pre2-49-20800.pt

work_dir: ./work_dir/ntu/xview/p2agcn_test_joint_SF_pre2
model_saved_name: ./runs/ntu_cv_p2agcn_test_joint_SF_pre2
save_score: True