# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/ShakeFiveP2_train/xview/train_data_joint.npy
  label_path: ./data/ShakeFiveP2_train/xview/train_label.pkl
  debug: False

# model
model: model.p2agcn.Model
model_args:
  num_class: 8
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
    num_node: 50


# test 
phase: test
device: [0]
test_batch_size: 64
#eights: ./runs/SF_p2agcn_joint-299-4200.pt
weights: ./runs/SF_p2agcn_joint-199-3500.pt

work_dir: ./work_dir/ntu/xview/p2agcn_train_joint_SF_testontrain
model_saved_name: ./runs/p2agcn_train_joint_SF_testontrain
save_score: True