work_dir: ./work_dir/ntu/xview/SF_p2agcn_joint
model_saved_name: ./runs/SF_p2agcn_joint
# feeder
feeder: feeders.feeder.Feeder
train_feeder_args:
  data_path: ./data/ShakeFiveP2_train/xview/train_data_joint.npy
  label_path: ./data/ShakeFiveP2_train/xview/train_label.pkl
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: -1
  normalization: False

test_feeder_args:
  data_path: ./data/ShakeFiveP2_train/xview/val_data_joint.npy
  label_path: ./data/ShakeFiveP2_train/xview/val_label.pkl

# model
model: model.p2agcn.Model
model_args:
  num_class: 8
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  graph_args:
    labeling_mode: 'spatial'
    num_node: 50

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [280, 290]

# training
device: [0]
batch_size: 4
test_batch_size: 4
num_epoch: 300
nesterov: True

############################################
weights: ./runs/SF_p2agcn_joint-199-3500.pt
start_epoch: 200
